"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _movie_card from './movie-card.bones.json'
import _movie_details from './movie-details.bones.json'

configureBoneyard({"color":"#d1d5db","darkColor":"#374151","animate":"shimmer","shimmerColor":"#f3f4f6","darkShimmerColor":"#6b7280","speed":"1.8s","shimmerAngle":110})

registerBones({
  "movie-card": _movie_card,
  "movie-details": _movie_details,
})
